bundle_cache: &bundle_cache
  bundle_cache:
    folder: /usr/local/bundle
    fingerprint_script: >
      echo $CIRRUS_TASK_NAME:$CIRRUS_OS:$RUBY_VERSION &&
      cat Gemfile &&
      cat flame-cli.gemspec
    populate_script: bundle update

test_task:
  container:
    matrix:
      image: ruby:2.5
      image: ruby:2.4
  <<: *bundle_cache
  environment:
    CODECOV_TOKEN: ENCRYPTED[5bfb9cd3d53a72c8423ce1b84b18cf7d30fbdcf3a56a25f9cd79dbdff1c3552542578272db8088ec27d7de7f2c363d72]
  test_script: bundle exec rake

rubocop_task:
  container:
    image: ruby:2.6
  <<: *bundle_cache
  rubocop_script: bundle exec rubocop
